=== PraneeshRV/Academics/Sem7/WebAppSec/web appl/LAB2/student.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Student">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="Name" type="xs:string"/>

                <xs:element name="RollNumber" type="xs:integer"/>

                <xs:element name="Subjects">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="Subject" maxOccurs="5" minOccurs="5">

                                <xs:complexType>

                                    <xs:sequence>

                                        <xs:element name="Name" type="xs:string"/>

                                        <xs:element name="Marks">

                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>

                                    </xs:sequence>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== PraneeshRV/Academics/Sem7/WebAppSec/web appl/LAB2/sample.xml
<?xml version="1.0" encoding="UTF-8"?>

<Student
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="student.xsd">

    <Name>Ponvedica M S</Name>

    <RollNumber>23034</RollNumber>

    <Subjects>

        <Subject>
            <Name>Web Appln</Name>
            <Marks>95</Marks>
        </Subject>

        <Subject>
            <Name>Secure Software</Name>
            <Marks>88</Marks>
        </Subject>

        <Subject>
            <Marks>91</Marks>
        </Subject>

        <Subject>
            <Name>Application Dev</Name>
            <Marks>76</Marks>
        </Subject>

        <Subject>
            <Name>ISRM</Name>
            <Marks>98</Marks>
        </Subject>

    </Subjects>

</Student>
